CREATE TABLE escorts_options (                                                          
	`optn_id` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,                                     
	`optn_pid` INT(13) UNSIGNED DEFAULT '0',                                                
	`optn_name` VARCHAR(128) DEFAULT NULL,                                                  
	`optn_value` VARCHAR(5000) DEFAULT NULL,                                                
	`optn_type` ENUM('int','decimal','varchar') DEFAULT NULL,                               
	`optn_area` ENUM('pictures','prices','profile','urls','votes','options') DEFAULT NULL,  
	`optn_description` VARCHAR(128) DEFAULT NULL,                                           
	PRIMARY KEY (`optn_id`),                                                                
	KEY `SORTORDER` (`optn_name`,`optn_type`,`optn_area`)                                   
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE escorts_pictures (                                             
	`id` INT(23) UNSIGNED NOT NULL AUTO_INCREMENT,                              
	`pid` INT(13) UNSIGNED NOT NULL DEFAULT '0',                                
	`title` VARCHAR(800) DEFAULT NULL,                                          
	`description` VARCHAR(5000) DEFAULT NULL,                                   
	`width` INT(6) DEFAULT NULL,                                                
	`height` INT(6) DEFAULT NULL,                                               
	`extension` VARCHAR(10) DEFAULT NULL,                                       
	`filename` VARCHAR(255) DEFAULT NULL,                                       
	`hits` MEDIUMINT(20) UNSIGNED DEFAULT '0',                                  
	`folder` ENUM('/uploads/','/uploads/escorts/') DEFAULT '/uploads/escorts/',  
	PRIMARY KEY (`id`),                                                         
	KEY `PIDGROUP` (`id`,`pid`)                                                 
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE escorts_prices (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
	`id` int(23) unsigned NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
	`pid` int(13) unsigned DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
	`type` enum('Weekdays Day','Weekends Day','Weekday Evening','Weekend Evening','Weekday Night','Weekend Night','Morning Weekday','Morning Weekend') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	`day` enum('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
	`time-start` enum('00:01 TO 04:00','04:01 TO 08:00','08:01 TO 12:00','12:01 TO 16:00','20:01 TO 24:00','01:00 TO 08:00','08:01 TO 12:00','12:01 TO 24:00') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	`time-end` enum('00:01 TO 04:00','04:01 TO 08:00','08:01 TO 12:00','12:01 TO 16:00','20:01 TO 24:00','01:00 TO 08:00','08:01 TO 12:00','12:01 TO 24:00') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	`event` enum('Dining','Sexual Passion','Sports','Casual Date','Discreet Affair','One on One Sex','Group Sex','Party Affair','Swinging', 'Other') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	`currency` enum('AFN','EUR','ALL','DZD','USD','EUR','AOA','XCD','XCD','ARS','AMD','AWG','AUD','EUR','AZN','BSD','BHD','BDT','BBD','BYR','EUR','BZD','XOF','BMD','INR','BTN','BOB','BOV','BAM','BWP','NOK','BRL','USD','BND','BGN','XOF','BIF','KHR','XAF','CAD','CVE','KYD','XAF','XAF','CLP','CLF','CNY','AUD','AUD','COP','COU','KMF','XAF','CDF','NZD','CRC','XOF','HRK','CUP','CUC','EUR','CZK','DKK','DJF','XCD','DOP','USD','EGP','SVC','USD','XAF','ERN','EEK','ETB','FKP','DKK','FJD','EUR','EUR','EUR','XPF','EUR','XAF','GMD','GEL','EUR','GHS','GIP','EUR','DKK','XCD','EUR','USD','GTQ','GBP','GNF','GWP','XOF','GYD','HTG','USD','AUD','EUR','HNL','HKD','HUF','ISK','INR','IDR','IRR','IQD','EUR','ILS','EUR','JMD','JPY','GBP','JOD','KZT','KES','AUD','KPW','KRW','KWD','KGS','LAK','LVL','LBP','ZAR','LSL','LRD','LYD','CHF','LTL','EUR','MOP','MKD','MGA','MWK','MYR','MVR','XOF','EUR','USD','EUR','MRO','MUR','EUR','MXN','MXV','USD','MDL','EUR','MNT','EUR','XCD','MAD','MZN','MMK','ZAR','NAD','AUD','NPR','EUR','ANG','XPF','NZD','NIO','XOF','NGN','NZD','AUD','USD','NOK','OMR','PKR','USD','PAB','USD','PGK','PYG','PEN','PHP','NZD','PLN','EUR','USD','QAR','EUR','RON','RUB','RWF','EUR','SHP','XCD','XCD','EUR','EUR','XCD','WST','EUR','STD','SAR','XOF','RSD','SCR','SLL','SGD','EUR','EUR','SBD','SOS','ZAR','EUR','LKR','SDG','SRD','NOK','SZL','SEK','CHF','CHW','CHE','SYP','TWD','TJS','TZS','THB','USD','XOF','NZD','TOP','TTD','TND','TRY','TMT','USD','AUD','UGX','UAH','AED','GBP','USD','USS','USN','USD','UYU','UYI','UZS','VUV','VEF','VND','USD','USD','XPF','MAD','YER','ZMK','ZWL','XAU','XBA','XBB','XBC','XBD','XDR','XPD','XPT','XAG','XFU','XTS','XXX') DEFAULT 'USD',  
	`description` varchar(5000) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
	`price` decimal(10,2) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
	PRIMARY KEY (`id`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
	KEY `SEARCHINDEX` (`pid`,`type`,`day`,`time-start`,`time-end`,`event`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE escorts_physique (                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
	`id` INT(13) UNSIGNED NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                              
	`pid` INT(13) UNSIGNED NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
	`race` ENUM('Native/Aboriginal','Caucasian','Africian','Latin','Asian','Other') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                               
	`height` ENUM('<5ft 0in / <152cm','5ft 0in / 152cm','5ft 1in / 155cm','5ft 2in / 157cm','5ft 3in / 160cm','5ft 4in / 162cm','5ft 5in / 165cm','5ft 6in / 167cm','5ft 7in / 170cm','5ft 8in / 172cm','5ft 9in / 175cm','5ft 10in / 177cm','5ft 11in / 180cm','6ft 0in / 183cm','6ft 1in / 186cm','6ft 2in / 188cm','6ft 3in / 190cm','6ft 4in / 193cm','6ft 5in / 195cm','6ft 6in / 198cm','>6ft 6in / >198cm') DEFAULT NULL,                                                                                
	`sex` ENUM('Male','Female','Transsexual') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	`weight` ENUM('<99lbs / <45kg','100-109lbs / 45-49kg','110-119lbs / 49-53kg','120-129lbs / 54-58kg','130-139lbs / 59-62kg','140-149lbs / 63-67kg','150-159lbs / 68-71kg','160-169lbs / 72-76kg','170-179lbs / 77-80kg','180-189lbs / 81-85kg','190-199lbs / 86-89kg','200-209lbs / 90-95kg','210-219lbs / 96-99kg','220-229lbs / 100-105kg','230-239lbs / 106-110kg','240-249lbs / 111-115kg','250-259lbs / 116-120kg','260-269lbs / 121-125kg','270-279lbs / 126-130kg','>300lbs / >131kg') DEFAULT NULL,  
	`dresssize` ENUM('6','8','10','12','14','16','18','20','22','24','26','28') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                   
	`shirtsize` ENUM('14in / 36cm','14.5in / 37cm','15in / 38cm','15.5in / 39cm','16in / 41cm','16.5in / 42cm','17in / 43cm','17.5in / 44cm','18in / 45cm','18.5in / 46cm','19in / 48cm','19.5in / 50cm','20in / 51cm') DEFAULT NULL,                                                                                                                                                                                                                                                                           
	`pantssize` ENUM('28in / 71cm','29in / 73cm','30in / 76cm','31in / 79cm','32in / 81cm','33in / 84cm','34in / 86cm','35in / 89cm','36in / 91cm','37in / 94cm','38in / 97cm','39in / 99cm','40in / 101cm','41in / 104cm','42in / 107cm','43in / 109cm','44in / 112cm','45in / 114cm','46in / 117cm') DEFAULT NULL,                                                                                                                                                                                            
	`bust` ENUM('A Cup','B Cup','C Cup','D Cup','E Cup','F Cup') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                  
	`hair` ENUM('Black Hair','Brown Hair','Auburn Hair','Red Hair','Blond Hair','Grey Hair','White Hair') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                         
	`eyes` ENUM('Amber Eyes','Blue Eyes','Brown Eyes','Gray Eyes','Green Eyes','Hazel Eyes','Red Eyes') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                           
	`bodyhair` ENUM('Smooth','Moderate','Hairy','Shaved','Waxed') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                 
	`penissize` ENUM('Under 5in / 11cm','5 - 7in / 12cm - 16cm','7 - 9in / 18 - 24cm','10 - 13in / 25 - 31cm','Over 13in / 33cm') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                 
	`foreskin` ENUM('Cut','Uncut') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	`position` ENUM('Top','Bottom','Verastile','Active','Passive','Top & Bottom','Top & Active','Bottom & Active','Top & Passive','Bottom & Passive') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                             
	`physique` ENUM('Slim','Athletic','Muscular','Average','Bear','Heavy') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                        
	`piercings` ENUM('Yes','No') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
	`tattoos` ENUM('Yes','No') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
	`drugs` ENUM('Yes','No') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	`smoking` ENUM('Yes','No') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
	`alcohol` ENUM('Yes','No') DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
	`actions` MEDIUMTEXT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
	`services` MEDIUMTEXT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	PRIMARY KEY (`id`,`pid`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	UNIQUE KEY `id` (`id`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	KEY `male` (`pid`,`race`,`height`,`sex`,`weight`,`shirtsize`,`pantssize`,`bust`,`hair`,`eyes`,`bodyhair`,`penissize`,`foreskin`,`position`,`physique`),                                                                                                                                                                                                                                                                                                                                                     
	KEY `female` (`pid`,`race`,`height`,`sex`,`weight`,`dresssize`,`bust`,`hair`,`eyes`,`position`,`physique`)                                                                                                                                                                                                                                                                                                                                                                                                  
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE escorts_profile (                                         
	`pid` INT(13) UNSIGNED NOT NULL AUTO_INCREMENT,                        
	`uid` INT(13) DEFAULT '0',                                             
	`alias` VARCHAR(128) DEFAULT NULL,                                     
	`name` VARCHAR(128) DEFAULT NULL,                                      
	`incall` ENUM('Yes','No') DEFAULT NULL,                                
	`outcall` ENUM('Yes','No') DEFAULT NULL,                               
	`sms` VARCHAR(64) DEFAULT NULL,                                        
	`mobile` VARCHAR(64) DEFAULT NULL,                                     
	`landline` VARCHAR(64) DEFAULT NULL,                                   
	`agency` ENUM('Yes','No') DEFAULT NULL,                                
	`age` VARCHAR(64) DEFAULT NULL,                                        
	`sexuality` ENUM('Hetrosexual','Bisexual','Homosexual') DEFAULT NULL,  
	`domains` MEDIUMTEXT,                                                  
	`locations` MEDIUMTEXT,                                                
	`tags` VARCHAR(255) DEFAULT NULL,                                      
	`slogon` VARCHAR(64) DEFAULT NULL,                                     
	`bio` MEDIUMTEXT,                                                      
	`columnone` MEDIUMTEXT,                                                
	`columntwo` MEDIUMTEXT,                                                
	`footer` MEDIUMTEXT,                                                   
	PRIMARY KEY (`pid`),                                                   
	KEY `SEARCHIDX1` (`uid`,`incall`,`outcall`,`agency`,`sexuality`)       
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE escorts_urls (                                                                                                              
	`id` INT(13) UNSIGNED NOT NULL AUTO_INCREMENT,                                                                                           
	`pid` INT(13) UNSIGNED DEFAULT NULL,                                                                                                     
	`type` ENUM('link','blog','facebook','twitter','profile','bio','interest','personal','myspace','google','eworld','other') DEFAULT NULL,  
	`url` MEDIUMTEXT,                                                                                                                        
	`other` VARCHAR(255) DEFAULT NULL,                                                                                                       
	PRIMARY KEY (`id`),                                                                                                                      
	KEY `SEARCHTYPEINDX1` (`pid`,`type`)                                                                                                     
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE escorts_votes (                    
	`id` INT(13) UNSIGNED NOT NULL AUTO_INCREMENT,  
	`pid` INT(13) UNSIGNED DEFAULT NULL,            
	`vote` FLOAT(4,2) DEFAULT '0.00',               
	`ip` VARCHAR(64) DEFAULT NULL,                  
	PRIMARY KEY (`id`),                             
	KEY `SEARCHIDX1` (`pid`,`ip`)                   
) ENGINE=MYISAM DEFAULT CHARSET=utf8;